# For mumbai
sources:
  - name: beetogether
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/{context.name:mattiapomelli/beetogether-mumbai}
  - name: talentlayer
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/{context.name2:talentlayer/talent-layer-mumbai}

documents:
  - ./src/queries/hiveAndIdentity.graphql
  - ./src/queries/proposalRequests.graphql