sources:
  - name: beetogether
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/mattiapomelli/talentlayer-zksynctestnet
  - name: talentlayer
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/mattiapomelli/beetogether-zksync

documents:
  - ./src/queries/hiveAndIdentity.graphql
  - ./src/queries/proposalRequests.graphql